cabal-version:      3.0
name:               haskell-examples
version:            0.1.0.0
synopsis:           Running examples of haskell concepts
license:            BSD3
author:             Nathan Bloomfield
maintainer:         nathan.bloomfield@tweag.io
copyright:          Modus Create
build-type:         Simple
extra-doc-files:    README.md

common warnings
    ghc-options: -Wall

executable haskell-examples
    import:           warnings
    main-is:          Main.hs
    build-depends:    base ^>=4.18.2.1
    hs-source-dirs:   app
    default-language: Haskell2010
